name = "app"
main = ".open-next/worker.js"
compatibility_date = "2026-05-27"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# `wrangler kv namespace create FRAME_DATA_KV` で取得した実 ID。
[[kv_namespaces]]
binding = "FRAME_DATA_KV"
id = "f89083c92a804b42a3f86c00458dcb4f"

# `wrangler d1 create pokken-db` で取得した実 ID。
[[d1_databases]]
binding = "DB"
database_name = "pokken-db"
database_id = "bdaddb40-8e75-4459-b943-a25512f91dd3"
migrations_dir = "migrations"
